-- PATCH_ID: 20260215010101_create_test_table
-- PATCH_TYPE: SCHEMA

CREATE TABLE IF NOT EXISTS test_table (
    id SERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    created_at TIMESTAMP DEFAULT NOW()
);
